services:

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: erp_usr
      POSTGRES_DB: erp
    volumes:
      - pgdata:/var/lib/postgresql/data   # ← fixed
    networks:
      - erp-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h 127.0.0.1 -p 5432" ]
      interval: 5s
      timeout: 3s
      retries: 20


  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      db:
        condition: service_healthy
    networks:
      - erp-network

networks:
  erp-network:
    driver: bridge

volumes:
  pgdata:
    driver: local